### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by gpcr** [WGLab/InterVar#1]
I am getting below error while running this command
Can you help, thanks 

./Intervar.py', '-c', 'config.ini'

  File "./Intervar.py", line 1631, in <module>
    main()
  File "./Intervar.py", line 1601, in main
    read_datasets()
  File "./Intervar.py", line 210, in read_datasets
    morbidmap_dict2[ cls2[2] ]='1'  # key as mim number
IndexError: list index out of range

**Comment by quanliustc** [comment]
please check the OMIM's morbidmap file, it should be like this: 
{Tuberculosis, protection against}, 607948 (3)|TIRAP, BACTS1|606252|11q24.2
I as the field delimiter, the third is the omim number , it will be used by intervar.

**Comment by gpcr** [comment]
I don't see the pipe "|" delimiter... its tab separated one...
Do you suggest any parsing to pipe?
Top few lines from morbidmap.txt file downloaded from the latest OMIM
# Copyright (c) 1966-2016 Johns Hopkins University. Use of this file adheres to the terms specified at http://omim.org/help/agreement.
# Generated: 2016-09-01
# See end of file for additional documentation on specific fields
# Phenotype     Gene Symbols    MIM Number      Cyto Location
17,20-lyase deficiency, isolated, 202110 (3)    CYP17A1, CYP17, P450C17 609300  10q24.32
17-alpha-hydroxylase/17,20-lyase deficiency, 202110 (3) CYP17A1, CYP17, P450C17 609300  10q24.32
17-beta-hydroxysteroid dehydrogenase X deficiency, 300438 (3)   HSD17B10, HADH2, ERAB, MRXS10   300256  Xp11.22
....
....
5-oxoprolinase deficiency, 260005 (3)   OPLAH, OPLAHD   614243  8q24.3
?2,4-dienoyl-CoA reductase deficiency, 616034 (3)       NADK2, C5orf33, DECRD   615787  5p13.2
?46XY sex reversal 5, 613080 (3)        CBX2, M33, SRXY5        602770  17q25.3
....

**Comment by quanliustc** [comment]
We will updated the new version. The   BP5 will be disabled, this file will be discarded.
As the morbidmap file is tab separated  now,
Temporarily,  you can just change the 214  line of Intervar.py :
cls2=line2.split('|')
to 
cls2=line2.split('\t')

It should be work.

**Comment by gpcr** [comment]
Thanks  did it in section #6
```
 201 #6.morbidmap from OMIM  for BP5 ,  multifactorial disorders  list
 202     try:
 203         fh = open(paras['morbidmap'], "r")
 204         str = fh.read()
 205         for line2 in str.split('\n'):
 206             cls2=line2.split('|') ### change to \t for tab seperated morbidmap file

```

BTW can we run we run on multi sample VCF file ?

**Comment by gpcr** [comment]
Does config.ini always need to be in current dir?
```
Notice: Your command of InterVar is ['/git/InterVar/Intervar.py', '--config=/project/config.ini', '-i', 'test.vcf', '--input_type=VCF', '-o', 'test_output']
Error: The default configure file of [ config.ini ] is not exit! Please redownload the InterVar.

```

**Comment by quanliustc** [comment]
Yes, the default config file of config.ini must always be put in the current dir as Intervar.py
then  you can add you own config file.

**Comment by quanliustc** [comment]
Yes, the default config file of config.ini must always be put in the current dir as Intervar.py
 then you can add you own config file. This is  safe for some options.
The options in user's config file will be updated.

**Comment by gpcr** [comment]
thanks ; always in current directory may not be a good choice, as we hope between projects and runs 
It will be great to refer to installed directory config file instead as default one?

**Comment by quanliustc** [comment]
The default config file must be there. While, the user's config file can be in any directory, also the options in the user's config file will replace the options in default config file and in effect.

**Comment by gpcr** [comment]
sorry, one more error, need your attention
```
python /git/InterVar/Intervar.py -i test_195997821.geno.vcf.gz --input_type=VCF -o test_195997821 |& tee Intervar.log

NOTICE: Finished reading 69881 lines from VCF file
NOTICE: A total of 69758 locus in VCF file passed QC threshold, representing 62012 SNPs (43658 transitions and 18354 transversions) and 7914 indels/substitutions
NOTICE: Finished writing 62012 SNP genotypes (43658 transitions and 18354 transversions) and 7914 indels/substitutions for 1 sample
=============================================================================
InterVar
Interpretation of Pathogenic/Benign for variants using python scripts of InterVar.
=============================================================================

%prog 0.1
Copyright (C) 2016 Wang Genomic Lab
Lisense GPL: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRENTY, to the extent permittable by law.
Written by Quan LI,leequan@gmail.com.
============================================================================

Notice: Your command of InterVar is ['/git/InterVar/Intervar.py', '-i', 'test_195997821.geno.vcf.gz', '--input_type=VCF', '-o', 'test_195997821']
INFO: The options are {'table_annovar': '/git/annovar/table_annovar.pl', 'exclude_snps': '/git/InterVar/intervardb/ext.variants.hg19', 'annotate_variation': '/git/annovar/annotate_variation.pl', 'ps4_snps': '/git/InterVar/intervardb/PS4.variants.hg19', 'bp1_genes': '/git/InterVar/intervardb/BP1.genes', 'current_version': 'Intervar_20151116', 'evidence_file': 'None', 'public_dev': 'https://github.com/WGLab/InterVar/releases', 'onetranscript': 'FALSE', 'database_names': 'refGene esp6500siv2_all avsnp147 dbnsfp30a clinvar_20160302 exac03 dbscsnv11 dbnsfp31a_interpro rmsk ensGene knownGene', 'buildver': 'hg19', 'inputfile_type': 'VCF', 'otherinfo': 'FALSE', 'mim2gene': '/git/InterVar/intervardb/mim2gene.txt', 'pp2_genes': '/git/InterVar/intervardb/PP2.genes', 'ps1_aa': '/git/InterVar/intervardb/PS1.AA.change.patho.hg19', 'morbidmap': '/git/InterVar/intervardb/morbidmap', 'outfile': 'test_195997821', 'csvout': 'FALSE', 'knowngenecanonical': '/git/InterVar/intervardb/knownGeneCanonical.txt', 'dot2underline': 'TRUE', 'convert2annovar': '/git/annovar/convert2annovar.pl -format vcf4 -withfreq', 'database_locat': '/git/annovar/humandb', 'database_intervar': '/git/InterVar/intervardb', 'lof_genes': '/git/InterVar/intervardb/PVS1.LOF.genes', 'disorder_cutoff': '0.01', 'mim_recessive': '/git/InterVar/intervardb/mim_recessive.txt', 'pm1_domain': '/git/InterVar/intervardb/PM1_domains_with_benigns', 'inputfile': 'test_195997821.geno.vcf.gz'}
Warning: the folder of /git/annovar/humandb is already created!
Warning: Begin to convert your vcf file of test_195997821.geno.vcf.gz to AVinput of Annovar ...
perl /git/annovar/convert2annovar.pl -format vcf4 -withfreq -format vcf4 test_195997821.geno.vcf.gz> test_195997821.geno.vcf.gz.avinput
**Error: can't read/write the annovar output file test_195997821.hg19_multianno.txt test_195997821.hg19_multianno.txt.grl_p**

```

**Comment by quanliustc** [comment]
check line 1686 and enable by remove "#":
check_annovar_result() 
lt will let  the annotation begin.

**Comment by gpcr** [comment]
Thanks , it is working now on single sample VCF
How we run we run on multi sample VCF file ?  It will be great to have this feature

**Comment by kkshaxqd** [comment]
I can not get the grl_p file when i run the command base an the example...
And how it work ??

**Comment by quanliustc** [comment]
Please show your command with the options, and also cat your config.ini file.

**Comment by kkshaxqd** [comment]
en, hello ,the command and the config.ini is this:
[@pdc InterVar-0.1.4]$ ./Intervar.py -c config.ini
[@pdc InterVar-0.1.4]$./Intervar.py  -b hg19   -i /mnt//qszhang/biodata/HUM079028-4I160057-A15_combined.R1.cleaned.vcf.avinput  --input_type=AVinput -t intervardb -o ./HUM079028-4I160057-A15_combined.R1.intervar.txt
======================config.ini======================
[InterVar]
buildver = hg19
# hg19 hg38
inputfile = example/ex1.avinput
# the inputfile and the path  example/ex1.avinput hg19_clinvar_20151201.avinput
inputfile_type = AVinput
# the input file type VCF,BED,AVinput
outfile = example/myanno
# the output file location and prefix of output file
database_intervar = intervardb
# the database location/dir for Intervar
lof_genes = %(database_intervar)s/PVS1.LOF.genes
pm1_domain = %(database_intervar)s/PM1_domains_with_benigns
mim2gene = %(database_intervar)s/mim2gene.txt
morbidmap = %(database_intervar)s/morbidmap
mim_recessive = %(database_intervar)s/mim_recessive.txt
mim_domin = %(database_intervar)s/mim_domin.txt
mim_adultonset = %(database_intervar)s/mim_adultonset.txt
mim_pheno = %(database_intervar)s/mim_pheno.txt
mim_orpha = %(database_intervar)s/mim_orpha.txt
orpha = %(database_intervar)s/orpha.txt
knowngenecanonical = %(database_intervar)s/knownGeneCanonical.txt
pp2_genes = %(database_intervar)s/PP2.genes
bp1_genes = %(database_intervar)s/BP1.genes
ps1_aa = %(database_intervar)s/PS1.AA.change.patho
# do not add the builder version
ps4_snps = %(database_intervar)s/PS4.variants
# do not add the builder version
bs2_snps = %(database_intervar)s/BS2_hom_het
# do not add the builder version
exclude_snps = %(database_intervar)s/ext.variants
# do not add the builder version,the variant in this list will not check the frequency, it is causal.
# the list should be tab-delimited,format like this:
# Chr Pos Ref_allele Alt_allele
evidence_file = None
# add your own Evidence file for each Variant:
# evidence file as tab-delimited,format like this:
# Chr Pos Ref_allele Alt_allele  PM1=1;BS2=1;PP2=0
disorder_cutoff = 0.01
#It is for BS1: Allele frequency is greater than expected for disorder
[InterVar_Bool]
onetranscript = FALSE
# print out only one transcript for exonic variants (default: all transcripts)
otherinfo = FALSE                
# print out otherinfo (infomration after fifth column in queryfile)
csvout  = TRUE                
# generate comma-delimited CSV file (default: tab-delimited txt file)
# --vcfinput                  specify that input is in VCF format and output will be in VCF format
dot2underline = TRUE            
# change dot in field name to underline (eg, Func.refGene to Func_refGene)
[Annovar]
convert2annovar = ./convert2annovar.pl
#convert input file to annovar format
table_annovar = ./table_annovar.pl
#
annotate_variation=  ./annotate_variation.pl
#
database_locat = humandb
# the database location/dir from annnovar   check if database file exists
database_names = refGene esp6500siv2_all 1000g2015aug avsnp144 dbnsfp30a clinvar_20160302 exac03 dbscsnv11 dbnsfp31a_interpro rmsk ensGene knownGene
# specify the database_names from ANNOVAR or UCSC
[Other]
current_version = Intervar_20151116
# pipeline version
public_dev = https://github.com/WGLab/InterVar/releases

**Comment by quanliustc** [comment]
Seems the config and command has no problem,

When you have trouble to run the example, Can you provide the screen output?

 

 

Best,

Quan LI

leequan@gmail.com

**Comment by kkshaxqd** [comment]
En, OK. 
the result is this:
![qq 20170215093239](https://cloud.githubusercontent.com/assets/20348472/22957314/683b447a-f362-11e6-80d3-fcffc9c2398d.png)
=========================
the begin is this:
![qq 20170215093525](https://cloud.githubusercontent.com/assets/20348472/22957296/50df3944-f362-11e6-8745-08256a81e0be.png)

**Comment by quanliustc** [comment]
what's your OMIM file version? it seems because  your OMIM file is not updated.

**Comment by kkshaxqd** [comment]
The OMIM file is download from the latest version.  en, it refer to the error like this:
![qq 20170215100810](https://cloud.githubusercontent.com/assets/20348472/22957915/afeb96ae-f366-11e6-8bac-79aedaf61bc7.png)
================================
the morbidmap.txt like this:
================================
# Copyright (c) 1966-2017 Johns Hopkins University. Use of this file adheres to the terms specified at https://omim.org/help/agreement.
# Generated: 2017-02-14
# See end of file for additional documentation on specific fields
# Phenotype	Gene Symbols	MIM Number	Cyto Location
17,20-lyase deficiency, isolated, 202110 (3)	CYP17A1, CYP17, P450C17	609300	10q24.32
17-alpha-hydroxylase/17,20-lyase deficiency, 202110 (3)	CYP17A1, CYP17, P450C17	609300	10q24.32
17-beta-hydroxysteroid dehydrogenase X deficiency, 300438 (3)	HSD17B10, HADH2, ERAB, MRXS10	300256	Xp11.22
2-aminoadipic 2-oxoadipic aciduria, 204750 (3)	DHTKD1, KIAA1630, AMOXAD, CMT2Q	614984	10p14
2-methylbutyrylglycinuria, 610006 (3)	ACADSB, SBCAD	600301	10q26.13
3-M syndrome 1, 273750 (3)	CUL7, 3M1	609577	6p21.1
3-M syndrome 2, 612921 (3)	OBSL1, KIAA0657, 3M2	610991	2q35
3-M syndrome 3, 614205 (3)	CCDC8, 3M3	614145	19q13.32
3-Methylcrotonyl-CoA carboxylase 1 deficiency, 210200 (3)	MCCC1, MCCA	609010	3q27.1
3-Methylcrotonyl-CoA carboxylase 2 deficiency, 210210 (3)	MCCC2, MCCB	609014	5q13.2
3-hydroxyacyl-CoA dehydrogenase deficiency, 231530 (3)	HADHSC, SCHAD, HHF4	601609	4q25
3-hydroxyisobutryl-CoA hydrolase deficiency, 250620 (3)	HIBCH	610690	2q32.2
3-methylglutaconic aciduria with deafness, encephalopathy, and Leigh-like syndrome, 614739 (3)	SERAC1, MEGDEL	614725	6q25.3
3-methylglutaconic aciduria, type I, 250950 (3)	AUH	600529	9q22.31
3-methylglutaconic aciduria, type III, 258501 (3)	OPA3, MGA3	606580	19q13.32
3-methylglutaconic aciduria, type V, 610198 (3)	DNAJC19, TIM14	608977	3q26.33
3-methylglutaconic aciduria, type VII, with cataracts, neurologic involvement and neutropenia, 616271 (3)	CLPB, SKD3, MEGCANN, MGCA7	616254	11q13.4
3-methylglutaconic aciduria, type VIII, 617248 (3)	HTRA2, OMI, PARK13, PRSS25, MGCA8	606441	2p13.1
3MC syndrome 1, 257920 (3)	MASP1, CRARF, 3MC1	600521	3q27.3
3MC syndrome 2, 265050 (3)	COLEC11, CLK1, 3MC2	612502	2p25.3

**Comment by kkshaxqd** [comment]
Oh,maybe is the config.ini!!!!    the morbidmap.txt is named morbidmap ...........   I try again and add the relevant values in config.ini , than it work!!!  THANK YOU , that's the reason...^-^...

**Comment by quanliustc** [comment]
Now, InterVar support the multiple samples in VCF.

For variants in each sample, Intervar will generate  according interpretation result.

 

Best,

Quan LI

leequan@gmail.com

**Comment by gpcr** [comment]
Wonderful!!!, Thanks I will check it out...using multi-vcf
One more feature request, if you can support other popular annotation tool SnpEff outputs

**Comment by kaichop** [comment]
You have to reformat the output from other tools to the simple
tab-delimited format to be used in InterVar.

**Comment by tiehan** [comment]
Error: can't read the OMIM  file /sam/InterVar/intervardb/mim2gene.txt
Error: Please download it from http://www.omim.org/downloads

Could you upload mim2gene.txt to intervardb folder ?
Thanks

**Comment by quanliustc** [comment]
Due the copyright issue, InterVar cannot put it in the intervardb folder, the user can easy download it: https://omim.org/static/omim/data/mim2gene.txt

 

 

 

 

Hi,

 

Best,

Quan LI

leequan@gmail.com
