### ISSUE TITLE
PS1 and PM5 also can't be assigned

### ISSUE THREAD

**Issue by tiehan** [WGLab/InterVar#12]
I run some snps by InerVar, but PS1 and PM5 can't be assigned. 

function check_PS1():
try:
                if  aa_changes_dict[keys_tmp2]:
                    PS1_t2=0
            except KeyError:
                for nt in ACGTs:
                    if nt != cls[Allels_flgs['Alt']]:
                        keys_tmp3=cls[Allels_flgs['Chr']]+"_"+cls[Allels_flgs['Start']]+"_"+cls[Allels_flgs['End']]+"_"+nt
                        try:
                            if aa_changes_dict[keys_tmp3] == aa_last:
                                PS1_t2=1
                        except KeyError:
                            pass

I wonder if keys_tmp2 in aa_changes_dict, why not  PS1_t2=1?

**Comment by quanliustc** [comment]
here,  PS1_t2 must be 0 firstly, it means this variant has the same allele change and also  the same amino acid change in the pathogenic databank, so it cannot assign PS1, if it is not the same allele change but the same amino acid change, PS1 will apply.

**Comment by quanliustc** [comment]
Also, maybe you can give me the list, I will track the details in the pathogenic allele change databset.

**Comment by tiehan** [comment]
I see . I wonder  that   some variants  in your aa_changes_dict will not be assigned PS1 and maybe  be assigned to VUS.

**Comment by quanliustc** [comment]
The dataset of amino acid change was based on pathogenic variants in clinvar, so it could miss  some real pathogenic variants.  And for the reported non-conflit pathogenic variants in disease variant dataset(such as clinvar), we will assign PP5.  PS1 only can be assigned when there are other nt change(not in the dataset we built ) with the same amino acid change. Also the same evidence we cannot use > twice.

**Comment by tiehan** [comment]
Thanks. I understand
