### ISSUE TITLE
dear lee, where can I download “the annotation result file from ANNOVAR”？the last two sentences of ERROR

### ISSUE THREAD

**Issue by pkphcwj** [WGLab/InterVar#19]
![img_0877](https://user-images.githubusercontent.com/31218514/31114100-0569e408-a84f-11e7-8e2e-bf4eff2d96fd.JPG)
wdeMacBook:InterVar-1.0.8 wj$ python Intervar.py -i example/ex1.avinput -o example/myanno --evidence_file=evdience.txt
=============================================================================
InterVar                                                                       
Interpretation of Pathogenic/Benign for variants using python scripts of InterVar.
=============================================================================

%prog 0.1.7 20170608
Written by Quan LI,leequan@gmail.com. 
InterVar is free for non-commercial use without warranty.
Please contact the authors for commercial use.
Copyright (C) 2016 Wang Genomic Lab
============================================================================

Notice: Your command of InterVar is ['Intervar.py', '-i', 'example/ex1.avinput', '-o', 'example/myanno', '--evidence_file=evdience.txt']
Warning: You provided your own evidence file [ evdience.txt ] for the InterVar.
Warning: Your specified evidence file [ evdience.txt ] is not here,please check the path of your evidence file.
         Your analysis will begin without your specified evidence.
INFO: The options are {'pp2_genes': 'intervardb/PP2.genes', 'inputfile': 'example/ex1.avinput', 'exclude_snps': 'intervardb/ext.variants.hg19', 'annotate_variation': './annotate_variation.pl', 'ps4_snps': 'intervardb/PS4.variants.hg19', 'mim_domin': 'intervardb/mim_domin.txt', 'current_version': 'Intervar_20170228', 'bs2_snps': 'intervardb/BS2_hom_het.hg19', 'evidence_file': 'evdience.txt', 'public_dev': 'https://github.com/WGLab/InterVar/releases', 'otherinfo': 'TRUE', 'database_names': 'refGene esp6500siv2_all 1000g201508 avsnp144 dbnsfp30a clinvar_20160302 exac03 dbscsnv11 dbnsfp31a_interpro rmsk ensGene knownGene', 'mim_pheno': 'intervardb/mim_pheno.txt', 'table_annovar': './table_annovar.pl', 'buildver': 'hg19', 'inputfile_type': 'AVinput', 'onetranscript': 'FALSE', 'mim2gene': 'intervardb/mim2gene.txt', 'orpha': 'intervardb/orpha.txt', 'ps1_aa': 'intervardb/PS1.AA.change.patho.hg19', 'mim_adultonset': 'intervardb/mim_adultonset.txt', 'knowngenecanonical': 'intervardb/knownGeneCanonical.txt', 'outfile': 'example/myanno', 'convert2annovar': './convert2annovar.pl', 'database_locat': 'humandb', 'database_intervar': 'intervardb', 'lof_genes': 'intervardb/PVS1.LOF.genes', 'disorder_cutoff': '0.01', 'mim_recessive': 'intervardb/mim_recessive.txt', 'pm1_domain': 'intervardb/PM1_domains_with_benigns', 'mim_orpha': 'intervardb/mim_orpha.txt', 'bp1_genes': 'intervardb/BP1.genes'} 
Warning: the folder of humandb is already created!
Warning: The Annovar dataset file of 1000g201508 is not in humandb,begin to download this humandb/hg19_1000g201508.txt ...
perl ./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar 1000g201508 humandb
NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_1000g201508.txt.gz ... Failed
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_1000g201508.txt.idx.gz ... Failed
WARNING: Some files cannot be downloaded, including http://www.openbioinformatics.org/annovar/download/hg19_1000g201508.txt.gz, http://www.openbioinformatics.org/annovar/download/hg19_1000g201508.txt.idx.gz
perl ./table_annovar.pl example/ex1.avinput humandb -buildver hg19 -remove -out example/myanno -protocol refGene,esp6500siv2_all,1000g2015aug_all,avsnp144,dbnsfp30a,clinvar_20160302,exac03,dbscsnv11,dbnsfp31a_interpro,rmsk,ensGene,knownGene  -operation  g,f,f,f,f,f,f,f,f,r,g,g   -nastring . --otherinfo 
Error: the required database file humandb/hg19_ALL.sites.2015_08.txt does not exist.
Warning: The InterVar seems not run correctly, please check your inputs , options and configure file!
**_**ERROR: The InterVar did not find the annotation result file from ANNOVAR!**_**
ERROR: The name of annotation result file should be like example/myanno*.hg19__multianno.txt
=============================================================================
Thanks for using InterVar!
Report bugs to leequan@gmail.com;
InterVar homepage: <http://wInterVar.wglab.org>
=============================================================================

**Comment by quanliustc** [comment]
what's your annovar version?
It seems the annovar annotation dataset of 1000g2015aug has not been downloaded.

**Comment by pkphcwj** [comment]
its the latest one, I downloaded here http://www.openbioinformatics.org/annovar/download/0wgxR2rIVP/annovar.latest.tar.gz

**Comment by pkphcwj** [comment]
I find the latest  intervar doesn't have the following two:
  inflating: InterVar-master/example/myanno.hg19_multianno.txt
  inflating: InterVar-master/example/myanno.hg19_multianno.txt.grl_p

**Comment by kaichop** [comment]
@pkphcwj you should NEVER share a URL that is protected to public sites. This is absolutely not allowed.

**Comment by kaichop** [comment]
InterVar is available at GitHub that you can download, but ANNOVAR requires a specific registration process. This is different.

**Comment by pkphcwj** [comment]
ok...I am so so so ...sorry for my fault!I will never do it again.i really need ur help for the use of intervar.

**Comment by pkphcwj** [comment]
I have redownlaoded the intervar and annovar ，but the myanno.hg19_multianno.txt and  annovar annotation dataset of 1000g2015aug still doesn't exist. whats wrong with it?

**Comment by quanliustc** [comment]
myanno.hg19_multianno.txt  is the example output of Annovar, 
Make sure your ANNOVAR is updated and also intervar updated , if the ANNOVAR and intervar are all new,
then you should can see :
====================================================
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_1000g2015aug.zip
====================================================
not download the  hg19_1000g201508.txt.gz

**Comment by quanliustc** [comment]
also update the config,ini file from githup,
and I can see your config,ini file also are outdated.

**Comment by pkphcwj** [comment]
@quanliustc THANK U SO MUCH! it works now,i added hg19_1000g201508aug in the humandb of intervar and went on!
