### ISSUE TITLE
Error downloading from Annovar

### ISSUE THREAD

**Issue by nickywhiff** [WGLab/InterVar#2]
I am getting the following notices when trying to run the tool:

NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_ALL.sites.2015_08.txt.gz ... Failed
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_ALL.sites.2015_08.txt.idx.gz ... Failed

These then result in an error:

Error: the required database file ../annovar/humandbm/hg19_ALL.sites.2015_08.txt does not exist.

When I go to the above addresses I get a URL not found error.

Please can you advise how to fix this?

Many thanks,
Nicky

**Comment by kaichop** [comment]
please read FAQ #1.

**Comment by nickywhiff** [comment]
As per the FAQ I have sent an email to leequan@gmail.com with the full command included

**Comment by quanliustc** [comment]
The web server of http://www.openbioinformatics.org/annovar was in manitenance. 

Now it is ok, you can download now.

--------------------------------------------------------------------------

NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_1000g2015aug.zip ... OK

NOTICE: Uncompressing downloaded files

 

Also you can try http://wintervar.wglab.org for searching when there are some downloading problems

 

Best,

Quan LI

leequan@gmail.com

**Comment by nickywhiff** [comment]
Hi Quan Li,

Thank you very much for this. When I run the command the tool still tries to download 'hg19_ALL.sites.2015_08.txt.gz' - the name of the file you sent is different. How do I tell the tool to download this alternative file?

Many thanks,
Nicky

**Comment by kaichop** [comment]
Nicky,
You are not supposed to download this file hg19_ALL.sites.2015_08.txt.gz,
which is why I asked you to provide your command. This file never existed.
-Kai

**Comment by nickywhiff** [comment]
Sorry Kai I might be being very stupid but when I run my command the script automatically tries to download this file. Full output is:


./Intervar.py -c config.ini --table_annovar=../annovar/table_annovar.pl --convert2annovar=../annovar/convert2annovar.pl --annotate_variation=../annovar/annotate_variation.pl --database_locat=../annovar/humandbm

=============================================================================

InterVar

Interpretation of Pathogenic/Benign for variants using python scripts of InterVar.

=============================================================================


%prog 0.1

Written by Quan LI,leequan@gmail.com.

InterVar is free for non-commercial use without warranty.

Please contact the authors for commercial use.

Copyright (C) 2016 Wang Genomic Lab

============================================================================


Notice: Your command of InterVar is ['./Intervar.py', '-c', 'config.ini', '--table_annovar=../annovar/table_annovar.pl', '--convert2annovar=../annovar/convert2annovar.pl', '--annotate_variation=../annovar/annotate_variation.pl', '--database_locat=../annovar/humandbm']

INFO: The options are {'pp2_genes': 'intervardb/PP2.genes', 'inputfile': 'example/ex1.avinput', 'exclude_snps': 'intervardb/ext.variants.hg19', 'annotate_variation': '../annovar/annotate_variation.pl', 'ps4_snps': 'intervardb/PS4.variants.hg19', 'mim_recessive': 'intervardb/mim_recessive.txt', 'current_version': 'Intervar_20151116', 'bs2_snps': 'intervardb/BS2_hom_het.hg19', 'evidence_file': 'None', 'public_dev': 'https://github.com/WGLab/InterVar/releases', 'otherinfo': 'FALSE', 'database_names': 'refGene esp6500siv2_all 1000g2015aug avsnp144 dbnsfp30a clinvar_20160302 exac03 dbscsnv11 dbnsfp31a_interpro rmsk ensGene knownGene', 'mim_pheno': 'intervardb/mim_pheno.txt', 'table_annovar': '../annovar/table_annovar.pl', 'buildver': 'hg19', 'inputfile_type': 'AVinput', 'onetranscript': 'FALSE', 'mim2gene': 'intervardb/mim2gene.txt', 'orpha': 'intervardb/orpha.txt', 'ps1_aa': 'intervardb/PS1.AA.change.patho.hg19', 'mim_adultonset': 'intervardb/mim_adultonset.txt', 'morbidmap': 'intervardb/morbidmap', 'outfile': 'example/myanno', 'csvout': 'FALSE', 'knowngenecanonical': 'intervardb/knownGeneCanonical.txt', 'dot2underline': 'TRUE', 'convert2annovar': '../annovar/convert2annovar.pl', 'database_locat': '../annovar/humandbm', 'database_intervar': 'intervardb', 'lof_genes': 'intervardb/PVS1.LOF.genes', 'disorder_cutoff': '0.01', 'mim_domin': 'intervardb/mim_domin.txt', 'pm1_domain': 'intervardb/PM1_domains_with_benigns', 'mim_orpha': 'intervardb/mim_orpha.txt', 'bp1_genes': 'intervardb/BP1.genes'}

Warning: the folder of ../annovar/humandbm is already created!

Warning: The Annovar dataset file of 1000g2015aug is not in ../annovar/humandbm,begin to download this ../annovar/humandbm/hg19_ALL.sites.2015_08.txt ...

perl ../annovar/annotate_variation.pl -buildver hg19 -downdb -webfrom annovar ALL.sites.2015_08 ../annovar/humandbm

NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done

NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_ALL.sites.2015_08.txt.gz ... Failed

NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_ALL.sites.2015_08.txt.idx.gz ... Failed

WARNING: Some files cannot be downloaded, including http://www.openbioinformatics.org/annovar/download/hg19_ALL.sites.2015_08.txt.idx.gz, http://www.openbioinformatics.org/annovar/download/hg19_ALL.sites.2015_08.txt.gz

perl ../annovar/table_annovar.pl example/ex1.avinput ../annovar/humandbm -buildver hg19 -remove -out example/myanno -protocol refGene,esp6500siv2_all,1000g2015aug_all,avsnp144,dbnsfp30a,clinvar_20160302,exac03,dbscsnv11,dbnsfp31a_interpro,rmsk,ensGene,knownGene  -operation  g,f,f,f,f,f,f,f,f,r,g,g   -nastring .

Error: the required database file ../annovar/humandbm/hg19_ALL.sites.2015_08.txt does not exist.

Error: can't read the OMIM morbidmap disorder file intervardb/morbidmap

Error: Please download it from http://www.omim.org/downloads



Best wishes,

Nicky

**Comment by kaichop** [comment]
you can run below to fix the problem for now so that you can run intervar
perl ../annovar/annotate_variation.pl -buildver hg19 -downdb -webfrom
annovar 1000g2015aug ../annovar/humandbm


It looks like a bug in intervar to download the file below, which Quan will
fix.

**Comment by kaichop** [comment]
Also see below, which you need to take care of yourself. We cannot include
omim in intervar distribution.

Error: can't read the OMIM morbidmap disorder file intervardb/morbidmap

Error: Please download it from http://www.omim.org/downloads

**Comment by quanliustc** [comment]
Hi, Nivky

 

Please redownload the InterVar, the download file problem for 1000g2015aug has been  fixed.

 

 

Best,

Quan LI

leequan@gmail.com
