### ISSUE TITLE
how can I use own config.ini ?

### ISSUE THREAD

**Issue by wengqi123** [WGLab/InterVar#20]
I creat my own config.ini ,and not in the InterVar path,but I use : python /path/to/InterVar.py -c /path/to/my_own_config.ini 
AND ERROR :  Error: The default configure file of [ config.ini ] is not here, exit! Please redownload the InterVar.
 SO ,HOW TO DO?

**Comment by quanliustc** [comment]
The default config.ini must be put in the same folder with  /path/to/InterVar.py 
This is to read some important options firstly, in case some user's file  lost some options.
Then will read your own config.ini,  also it will update the user's  options.

**Comment by wengqi123** [comment]
the default config.ini in the same  folder with InterVar.py,I mean, if I can creat other config.ini? 
like sample.ini,only change input and output path ,and run  :python /path/to/InterVar.py -c /path/to/sample.ini

**Comment by quanliustc** [comment]
Yes, you can create and use you own sample.ini by -c option, but confirm the default config.ini is there.
The Intervar will use your option in your config file.

**Comment by MHasnatA95** [comment]
Hi,

I am having the same problem:

Notice: Your command of InterVar is ['C:\\Users\\Hasnat\\Documents\\InterVar\\InterVar-master\\Intervar.py', '[config.ini]', '-c', 'config.ini']
Error: The default configure file of [ config.ini ] is not here, exit! Please redownload the InterVar.

The config.in file is in the same folder as InterVar.py and I am simply trying to use the default config.in file.

**Comment by quanliustc** [comment]
Try to cd the intervar folder:  'C:\Users\Hasnat\Documents\InterVar\InterVar-master\'
and run it again .

**Comment by MHasnatA95** [comment]
That seems to have worked, thank you.

**Comment by quanliustc** [comment]
thanks and fixed in the new version
