### ISSUE TITLE
ValueError: could not convert string to float: '.'

### ISSUE THREAD

**Issue by ZhenhongJiang** [WGLab/InterVar#23]
Hi,when I  run the example in config.ini with this command:
python InterVar.py -c config.ini
I got the following error. The version of python and ANNOVAR on my computer are 3.5.2 and 2017-07-17 respectively.

Notice: Begin the variants interpretation by InterVar 
Traceback (most recent call last):
  File "Intervar.py", line 2083, in <module>
    main()
  File "Intervar.py", line 2052, in main
    sum2=my_inter_var(annovar_outfile)
  File "Intervar.py", line 1805, in my_inter_var
    intervar_bp=assign(BP,line,Freqs_flgs,Funcanno_flgs,Allels_flgs)
  File "Intervar.py", line 1680, in assign
    BP7=check_BP7(line,Funcanno_flgs,Allels_flgs)
  File "Intervar.py", line 1601, in check_BP7
    if float(cls[Funcanno_flgs['GERP++_RS']]) <= float(cutoff_conserv) or cls[Funcanno_flgs['GERP++_RS']] == '.' :
ValueError: could not convert string to float: '.'

Can you help me? Thanks.

**Comment by quanliustc** [comment]
Please update  the intervar by:

https://github.com/WGLab/InterVar/archive/master.zip

 

 

Best,

Quan LI, Ph.D

 <mailto:leequan@gmail.com> leequan@gmail.com

 <mailto:Quan.Li@uhnresearch.ca> Quan.Li@uhnresearch.ca 

 <http://www.quanli.tk> http://www.quanli.tk

**Comment by ZhenhongJiang** [comment]
Thank you very much. Everything works fine according to your advice.
Best wishes， 

Zhenhong Jiang, PhD

Jiangxi Province Key Laboratory of Molecular Medicine

Email: jxzhjiang@163.com
