### ISSUE TITLE
Unable to see Orphanet Disease Title

### ISSUE THREAD

**Issue by cholyavkin** [WGLab/InterVar#30]
As you know, the output of _Intervar.py_ contains two columns related with Orhphanet: 

- **OrphaNumber:** Contains the Orpha IDs which are related with the gene of interest.
- **Orpha:** Contains detailed information about the Orphanet record such as synonyms, prevalence etc.

However, none of these columns contains exact title of the disorder. For example for the SNP with Orpha ID#319646, the **Orpha** column looks like that:

`"319646|CDG syndrome type It<br>CDG-It<br>CDG1T|<1 / 1 000 000|Autosomal recessive|Neonatal<br>Infancy|614921 ~"`

and the **OrphaNumber** column is:
`319646;`

The names seen in record (_CDG syndrome type It_) is a synonym of actual disorder which is [PGM1-CDG](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=21686&Disease_Disease_Search_diseaseGroup=319646&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=PGM1-CDG&title=PGM1-CDG&search=Disease_Search_Simple). How can I extract the real disorder name with using Intervar instead of synonyms?

**Comment by quanliustc** [comment]
When I built the database, these are all the information. For your mentioned exact or full title, I did not have it. And you have the orphaID, you can get the complete information from Orpha website.

**Comment by cholyavkin** [comment]
Thank you for the reply. As you said, I updated the intervardb/orpha.txt file and replaced synonyms with full title. I'm sharing the file: [orpha_updated.txt](https://github.com/WGLab/InterVar/files/2116805/orpha_updated.txt)

**Comment by kaichop** [comment]
Thank you!

**Comment by quanliustc** [comment]
Thanks!  I will update it!
