### ISSUE TITLE
http://wintervar.wglab.org/ site is down

### ISSUE THREAD

**Issue by redmoon6584** [WGLab/InterVar#35]
Hello, I've been trying to access the InterVar website since last Thursday/Friday.  The site seems to be down.  Could you let me know if a fix is in progress and the timeline for it to come back online?

**Comment by quanliustc** [comment]
HI, the Web server is under moving and upgrade, will be available soon.
Thanks!

**Comment by quanliustc** [comment]
wintervar is back with the same url: http://wintervar.wglab.org, but you maybe need flush the DNS cache, if still has problem to visit.
