### ISSUE TITLE
check_PS1() won't return 1

### ISSUE THREAD

**Issue by tiehan** [WGLab/InterVar#4]
check_PS1() won't return 1 and PS1 will still 0.

----------------------------------------------------------------
def check_PS1(line, Funcanno_flgs, Allels_flgs, aa_changes_dict):
    '''
    PS1 Same amino acid change as a previously established pathogenic variant regardless of nucleotide change
    Example: Val->Leu caused by either G>C or G>T in the same codon
    AAChange.refGene
    NOD2:NM_001293557:exon3:c.C2023T:p.R675W,NOD2:NM_022162:exon4:c.C2104T:p.R702W
    '''

    PS1 = 0
    PS1_t1 = 0
    PS1_t2 = 0
    PS1_t3 = 0
    dbscSNV_cutoff = 0.6  # either score(ada and rf) >0.6 as splicealtering
    cls = line.split('\t')
    funcs_tmp = ["missense", "nonsynony"]
    ACGTs = ["A", "C", "G", "T"]
    line_tmp = cls[Funcanno_flgs['Func.refGene']] + " " + cls[Funcanno_flgs['ExonicFunc.refGene']]

    for fc in funcs_tmp:
        if line_tmp.find(fc) >= 0:
            PS1_t1 = 1;
            # need to wait to check Same amino acid change as a previously pathogenic variant
            line_tmp2 = cls[Funcanno_flgs['AAChange.refGene']]
            cls0 = line_tmp2.split(',')
            cls0_1 = cls0[0].split(':')
            aa = cls0_1[4]
            aa_last = aa[len(aa) - 1:]
            keys_tmp2 = cls[Allels_flgs['Chr']] + "_" + cls[Allels_flgs['Start']] + "_" + cls[
                Allels_flgs['End']] + "_" + cls[Allels_flgs['Alt']]
            try:
                if aa_changes_dict[keys_tmp2]:
                    PS1_t2 = 0
            except KeyError:
                for nt in ACGTs:
                    if nt != cls[Allels_flgs['Alt']]:
                        keys_tmp3 = cls[Allels_flgs['Chr']] + "_" + cls[Allels_flgs['Start']] +\
                                    "_" + cls[Allels_flgs['End']] + "_" + nt
                        try:
                            if aa_changes_dict[keys_tmp3] == aa_last:
                                PS1_t2 = 1
                        except KeyError:
                            pass
                        else:
                            pass
            else:
                pass
    try:
        if float(cls[Funcanno_flgs['dbscSNV_RF_SCORE']]) > dbscSNV_cutoff or float(
                cls[Funcanno_flgs['dbscSNV_ADA_SCORE']]) > dbscSNV_cutoff:  # means alter the splicing
            PS1_t3 = 1
    except ValueError:
        pass
    else:
        pass

    if PS1_t1 != 0 and PS1_t2 != 0:
        if PS1_t3 == 1:  # remove the splicing affect
            PS1 = 0
    return (PS1)

**Comment by quanliustc** [comment]
fixed, PS1=1 was  there before 
"if PS1_t3 == 1:  # remove the splicing affect"

**Comment by tiehan** [comment]
Please check again,PS1 still be 1
-------------------------------
    if PS1_t1 !=0 and PS1_t2 != 0 :
        PS1=0
        if PS1_t3 ==1: # remove the splicing affect 
            PS1=0
    return(PS1)

**Comment by quanliustc** [comment]
typo, change the line PS1=0 to PS1=1
