### ISSUE TITLE
ANNOVAR new version is available ... Failed

### ISSUE THREAD

**Issue by HJTsai** [WGLab/InterVar#41]
Hello,

The latest version of ANNOVAR (2018Apr16) in my computer, however web-based checking to see whether ANNOVAR new version is available ... Failed
Database also cannot be downloaded.
How to solve this problem?
Thanks

Tsai

**Comment by kaichop** [comment]
We will try bring the server up online by this weekend.

**Comment by kaichop** [comment]
ANNOVAR site is online now.

**Comment by HJTsai** [comment]
Thank you.
