### ISSUE TITLE
Download and unzip error for ljb26_all and 1000g2015aug.

### ISSUE THREAD

**Issue by hiroyukikato911** [WGLab/InterVar#44]
Hi,

I'm trying the following command
**perl annotate_variation.pl -downdb -webfrom annovar --buildver hg19 1000g2015aug humandb/** 
**perl annotate_variation.pl -downdb -webfrom annovar --buildver hg19 ljb26_all humandb/**

However, I get the following error.

_NOTICE: Uncompressing downloaded files
**unzip:  cannot find or open hg19_1000g2015aug.zip, hg19_1000g2015aug.zip.zip or hg19_1000g2015aug.zip.ZIP.**
NOTICE: Finished downloading annotation files for hg19 build version, with files saved at the 'humandb' directory Done
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_ljb26_all.txt.idx.gz ... Done
NOTICE: Uncompressing downloaded files
**gunzip: hg19_ljb26_all.txt.gz: unexpected end of file
gunzip: hg19_ljb26_all.txt.gz: uncompress failed**
NOTICE: Finished downloading annotation files for hg19 build version, with files saved at the 'humandb' directory_

It seems unzip error due to failure downloading.
"hg19_ljb26_all.txt.gz" file size is 1.08GB which seems to be smaller than expected.
I also read the issue #2, but still can't figure out how to solve it.
Other file such as esp6500siv2_all, exac03 were successfully downloaded in similar command.

I'm using macOS High Sierra, version 10.13.6.
I downloaded the latest version of Annovar on May 14.

Any help would be appreciated.

Best regards,
Hiroyuki

**Comment by kaichop** [comment]
The download was not complete, just try download again.
ljb26 is extremely outdated now and you should not use it. You can use
dbnsfp instead.

**Comment by hiroyukikato911** [comment]
Hi Kai,

Thank you so much for your advice!
I tried more than 5 times using server through my lab which never worked.
However, it was successfully downloaded at different server.

So perhaps it was server problem.
Thank you so much again!

Best regards,
