### ISSUE TITLE
OMIM Phenotype name

### ISSUE THREAD

**Issue by arumds** [WGLab/InterVar#56]
Dear Lee,

Would it be possible to have the phenotype name in the "Phenotype_OMIM" instead of the OMIM ID?

**Comment by quanliustc** [comment]
Hi arumds,
As OMIM only publish the mim2gene.txt without  licensing and registration, if we publish information more than this file, could bring licensing issue,so we can not put complete information in the results, only put their omim link for use to quickly check.
