### ISSUE TITLE
ERROR in Running with system command <coding_change.pl

### ISSUE THREAD

**Issue by lincj1994** [WGLab/InterVar#57]
HI, I was running InterVar on the ex1.avinput. An error was reported like this: 
Can't exec "coding_change.pl": No such file or directory at ./table_annovar.pl line 455.

Here is the line 455 of table_annovar.pl: 
system ($sc) and die "Error running system command: <$sc>\n";

Any help is appreciated.

**Comment by kaichop** [comment]
depending on whether you are using Windows or Linux or Mac, it could be a
PATH set up issue. You can try add ANNOVAR directory to your PATH so the
program can be executed.

**Comment by lincj1994** [comment]
@kaichop Thanks. I have another question about the input type. In the article of "InterVar: Clinical Interpretation of Genetic Variants by the 2015 ACMG-AMP Guidelines", it stated that "The runtime can be greatly reduced to <5 min (~0.1 ms per variant) if an existing ANNOVAR annotation file is already available". I dont know which argument was used to specified the input that has already been annotated by ANNOVAR.

**Comment by quanliustc** [comment]
You can add:

 

    --skip_annovar      Skip the Annovar annotation, this can be true only

                        after you  already got the annovar's annotation

                        results

 

also please check the manual  to make this work no problem.

 

Best,

Quan LI, Ph.D

http://www.quanli.org

**Comment by lincj1994** [comment]
> You can add:
> […](#)
> --skip_annovar Skip the Annovar annotation, this can be true only after you already got the annovar's annotation results also please check the manual to make this work no problem. Best, Quan LI, Ph.D http://www.quanli.org

Thanks for the reply. Besides, the intervar requires the input file to include Chr, Position_Start, Position_End, Reference_allele, and Alternative_allele only. But I have an input file which contains tumor_sample_barcode also, I dont know how to keep the column of tumor_sample_barcode in the output.

**Comment by lincj1994** [comment]
> you can put in in the six column, then this information will be in the last column as "Otherinfo" in the final output.

I have put it in the sixth column. But in the final output, the "Otherinfo" column contains Chromosome only, same as Column one.

**Comment by quanliustc** [comment]
set the input file as tab-separated , and also  make sure you chromosome name start as chr not Chr

**Comment by lincj1994** [comment]
> set the input file as tab-separated , and also make sure you chromosome name start as chr not Chr

Thank you. My input file is .tsv. The input file is organized as the example provided by InterVar, no column name and no "chr" or "Chr" before the chromosome name. Here are the first five rows of my input and the six columns represent chromosome, start, end, Ref, Alt, sample barcode:

1 | 2116360 | 2116360 | G | T | 2002798
1 | 9775906 | 9775906 | G | C | 2000934
1 | 9777168 | 9777168 | T | G | 2001877
1 | 11188610 | 11188610 | C | CACTGGTT | 1800215
1 | 11293545 | 11293545 | C | A | 1801028
1 | 16254585 | 16254585 | G | A | 1800612

**Comment by lincj1994** [comment]
> > set the input file as tab-separated , and also make sure you chromosome name start as chr not Chr
> 
> Thank you. My input file is .tsv. The input file is organized as the example provided by InterVar, no column name and no "chr" or "Chr" as the prefix before the chromosome name. Here are the first five rows of my input and the six columns represent chromosome, start, end, Ref, Alt, sample barcode:
> 
> 1 | 2116360 | 2116360 | G | T | 2002798
> 1 | 9775906 | 9775906 | G | C | 2000934
> 1 | 9777168 | 9777168 | T | G | 2001877
> 1 | 11188610 | 11188610 | C | CACTGGTT | 1800215
> 1 | 11293545 | 11293545 | C | A | 1801028
> 1 | 16254585 | 16254585 | G | A | 1800612

Also, I've tried the input below and the Otherinfo column still didnt include the sample barcode.
chr1 | 2116360 | 2116360 | G | T | 2002798
chr1 | 9775906 | 9775906 | G | C | 2000934
chr1 | 9777168 | 9777168 | T | G | 2001877
chr1 | 11188610 | 11188610 | C | CACTGGTT | 1800215
chr1 | 11293545 | 11293545 | C | A | 1801028
chr1 | 16254585 | 16254585 | G | A | 1800612

**Comment by quanliustc** [comment]
I think I found the reason why your sample information lost:

As Annovar’s output changed the sample information column name from “Otherinfo” to “Otherinfo1”.

Will revise this.

 

Best,

Quan LI, Ph.D

http://www.quanli.org

**Comment by quanliustc** [comment]
Otherinfo1 or Otherinfo are fixed.

**Comment by lincj1994** [comment]
Hi. CancerVar has the same problem.

**Comment by lincj1994** [comment]
> Otherinfo1 or Otherinfo are fixed.

Hi. CancerVar has the same problem.
