### ISSUE TITLE
BS1 and PP5 problems

### ISSUE THREAD

**Issue by Bin-Guan** [WGLab/InterVar#59]
Hello, I noticed that the current version has the following two issues. 1). check_BS1 function did not use paras['disorder_cutoff'] from config.ini file. The line 1363-1364 can be edited as "else: pass" from "else: cutoff=0.005".
2). check_PP5 function, line 1330 should be  clinvar_bp.find("onflicting")==-1 instead of 0. 
Thank you.

**Comment by quanliustc** [comment]
Fixed and Thanks!

**Comment by Bin-Guan** [comment]
Thanks and I like InterVar.

**Comment by lacek** [comment]
The InterVar paper and the config file suggest 1% (0.01): https://github.com/WGLab/InterVar/blob/master/config.ini#L42
But the config parser gives warning and suggest to use 0.005.

Which cutoff should be taken and what's the rationale?

Thank you.

**Comment by quanliustc** [comment]
When invoke BS1, as the variant frequency of pathogenic variant in different populations some time may vary , so generally, if you have no idea the diseases(for all diseases), you could use 0.5% , while 1% may get more confident benign.
And if you focus on some specific disease, you could change this cutoff to the expected frequency for your interested disease.
