### ISSUE TITLE
check_PVS()

### ISSUE THREAD

**Issue by tiehan** [WGLab/InterVar#6]
question1:

In ACMG Paper, it writes "in the last 50 base pairs of the penultimate exon"  ,
why in our interVar the last 50 base for the last exon ???

          try:
                if (float(knownGeneCanonical_ed_dict[trans_id])-float( cls[Allels_flgs['Start']]  ))<50: # means close  3' of gene 50 bp.
                 PVS=0
            except ValueError:
                pass
            else:
                pass

question2:
The ACMG paper means the last base ? why in our interVar it becomes 1 nor last exon?

            if exon==exon_lth or exon =="exon1": # not 1 or last exon
                PVS=0

**Comment by quanliustc** [comment]
the ACMG'criteria still has some disputation,so you will find some criteria has small difference,
these kind of  slight  difference was suggested by reviewers, but we can change back to totally follow the guideline.

**Comment by tiehan** [comment]
Can be one variant assigned PVS1 and BA1?
rs12077871 use to test , and it is assigned PVS1 and BA1?
Can they both exist? I review your code, and I don't see allele frequency to filter PVS1.

**Comment by quanliustc** [comment]
Fot this variant(G>A), it is stopgain, so PVS1 is assigned, also the MAF insome cohort is >5%, so BA1 is assigned. For this variant, the intervar assigned as Benign, from InterVar side, it is no problem.   We suggest the manual step after the automated interpreation, if you have more evidence of pathogenic.

**Comment by tiehan** [comment]
Thanks. I wonder whether we need to set frequency cutoff (eg: 5%) in the judgement of PVS1.  In your code, PVS1 can be assigned to one snp whose frequency cutoff >0.5% ?
