### ISSUE TITLE
How to assign the annovar annotation file to InterVar when skipping annovar?

### ISSUE THREAD

**Issue by lincj1994** [WGLab/InterVar#65]
Hi.
I have a variant dataset which has been annotated by Annovar. So I'd like to skip annovar when performing InterVar but it returned an error:
```
ERROR: The InterVar did not find the annotation result file from ANNOVAR!
ERROR: The name of annotation result file should be like /home/lcj/lincj/CBCGA/WES/InterVar-output/CBCGAWES_anno1*.hg19__multianno.
```
I have checked the help message of Intervar.py but there was no argument to assign the annotation file. So in the configure.ini. 
Besides, no `*.hg19_multianno file` was found in the destination format.

**Comment by quanliustc** [comment]
suppose, your input file is **test2.av** and your Annovar ouput file name as:  **test4.av**.hg19_multianno.txt; then you could run as:  python Intervar.py  -b hg19 -i **test2.av** --skip_annovar -o  **test4.av**

**Comment by lincj1994** [comment]
Thanks for your reply. I dont know if there is any example data for annovar output file that can be identified by InterVar.

**Comment by yinbinqiu** [comment]
hello, how do you solve this problem?

**Comment by yinbinqiu** [comment]
> 

hello, how do you solve this problem?
