### ISSUE TITLE
[Question] How to read triggered ACMG rules from InterVar output

### ISSUE THREAD

**Issue by damianosmel** [WGLab/InterVar#68]
Dear InterVar developers,

First, thank you for developing the CLI and web application of InterVar.

After installing InterVar and running it for my vcf of interest, I get the output file with classified variants. This tabular file contain a column named "InterVar: InterVar and Evidence" there for a example variant I get:
`InterVar: Likely benign PVS1=0 PS=[0, 0, 0, 0, 0] PM=[0, 0, 0, 0, 0, 0, 0] PP=[0, 0, 0, 0, 0, 0] BA1=0 BS=[1, 0, 0, 0, 0] BP=[1, 0, 0, 0, 0, 1, 0, 0] `

I feel that each 0 (or 1) shows deactivation or activation of a evidence rule. 
However, by original ACMG [publication](https://pubmed.ncbi.nlm.nih.gov/25741868/) there are 4 Pathogenic Strong evidence-based rules and on the PS output there are **5 zeros**.
Please may you explain me why is that?

Grateful to your help to ensure the exact interpretation of InterVar output.

Thank you in advance!
Damianos

**Comment by quanliustc** [comment]
The last is for user additional criteria, so for each of category, there one user specified criteria in the last, default is 0.

**Comment by damianosmel** [comment]
Dear Quan Li,

grace to your explanation, I understand the output format.

Thank you!
Damianos
