### ISSUE TITLE
I just want to know the acmg result and NGF of a certain mutation site 

### ISSUE THREAD

**Issue by Zzc79** [WGLab/InterVar#89]
I just want to know the acmg result and NGF of A certain mutation site (such as chr1:115828756 G>A). How can I use intervar and what should I input

**Comment by kaichop** [comment]
you can use wet intervar at wintervar.wglab.org

**Comment by quanliustc** [comment]
Please visit the web server of InterVar(http://wintervar.wglab.org/), then Query by genomic coordinate.
