### ISSUE TITLE
The evidence file format should be avinput like or vcf like?

### ISSUE THREAD

**Issue by MingchenInSZ** [WGLab/InterVar#96]
Hi,
I want to prepare the evidence file for my annotation, and I checked the guide,  found "Chr Pos Ref_allele Alt_allele  evidence_list
" and tab seperated, without specifying the ref and alt should be avinput like or vcf like?

Looking forward to your reply.   Thanks a lot.

**Comment by quanliustc** [comment]
The ref and alt should be avinput like.

**Comment by MingchenInSZ** [comment]
@quanliustc Copy! Thanks a lot.
